#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,	LiftRU,	tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,	LiftRD,	tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,	LiftLU,	tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,	LiftLD,	tmotorVex393_MC29, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma CompetitionControl(Competition)

#pragma autonomousDuration(15)
#pragma UserControlDuration(120)

#include "Vex_Competition_Includes.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pre_auton (){
}

/* ^ im pretty sure the void pre_auton has to be here, not quite sure why yet ^
// \/ This Here is just a test autonomous to see if it works, we will be changing this */

task autonomous()
	{
		motor[FR]=-127;
		motor[FL]=-127;
		motor[BR]=-127;
		motor[BL]=-127;
		wait1Msec(1000);

		motor[FR]=0;
		motor[FL]=0;
		motor[BR]=0;
		motor[BL]=0;
		wait1Msec(20);

		motor[FR]=127;
		motor[FL]= -127;
		motor[BR]=127;
		motor[BL]= -127;
		wait1Msec(500);

		motor[FR]=0;
		motor[FL]=0;
		motor[BR]=0;
		motor[BL]=0;
		wait1Msec(20);

		motor[FR]=-127;
		motor[FL]= -127;
		motor[BR]=-127;
		motor[BL]= -127;
		wait1Msec(1000);

		motor[FR]=0;
		motor[FL]=0;
		motor[BR]=0;
		motor[BL]=0;
		wait1Msec(20);

		motor[LiftRU]=127;
		motor[LiftRD]=127;
		motor[LiftLU]=127;
		motor[LiftLD]=127;
		wait1Msec(750);

		motor[LiftRU]=0;
		motor[LiftRD]=0;
		motor[LiftLU]=0;
		motor[LiftLD]=0;
		wait1Msec(20);
	}
	/*  moves back for 1 sec, point turns left for a half sec
	 (will be adjusted to turn at the correct angle), moves
	 backward again for a sec, then moves the lift up for
	 3/4 of a second*/
task usercontrol()
{while (1==1)
	{
		//Right joystick controls right wheels
		motor[FL] = vexRT[Ch2];
		motor[BL]  = vexRT[Ch2];
		//Left joystick controls left wheels
		motor[FR] = vexRT[Ch3];
		motor[BR]  = vexRT[Ch3];
		int x = 0;
		if(vexRT[Btn8D])
		{
			startTask(autonomous);
			while(x <= 15000){
				wait1Msec(1);
				x++;
			}
		}
		/* press the bottom button of the right buttons to 
		start the autonomous*/
		if (vexRT[Btn6U] == 1)
		{
		motor[LiftRU] = 127;
		motor[LiftRD] = 127;
		motor[LiftLU] = 127;
		motor[LiftLD] = 127;
		/*this will move both sides of the lift up when
		button 6U ( the upper right button on the back)
		is pressed*/
		}
		else if (vexRT[Btn6D] == 1)
		{
		motor[LiftRU] = -127;
		motor[LiftRD] = -127;
		motor[LiftLU] = -127;
		motor[LiftLD] = -127;
		/* this will move both sides of the lift down when
		button 6D ( the lower right button on the back)
		is pressed */
		}
		else
		{
		motor[LiftRU] = 0;
		motor[LiftRD] = 0;
		motor[LiftLU] = 0;
		motor[LiftLD] = 0;
		/* this will stop the lift when neither of those
		 buttons are being pressed */
		}
	}
}
/* that's it for now (we will wright the
 date from now on) 10/12/16 */
